name: Windows Build CI

on: [workflow_dispatch]

jobs:
  build:
    name: Windows
    runs-on: windows-${{ matrix.version }}
    strategy:
      matrix:
        arch: [32, 64]
        build: [release]
        version: [2019, 2022]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install actuate 1.8.9 --quiet
          haxelib --never git flixel https://github.com/mcagabe19/flixel-4.9.0.git
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib git linc_luajit https://github.com/sirox228/linc_luajit.git
          haxelib git polymod https://github.com/mcagabe19/polymod-for-kade1.5.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git
          haxelib set openfl 9.1.0
          haxelib set lime 7.9.0
      - name: Compile
        run: haxelib run lime build windows -D mobileC -${{ matrix.arch }} -${{ matrix.build }} -D no-compilation -D macro-times -D analyzer-optimize
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build-${{ matrix.version }}-${{ matrix.arch }}-${{ matrix.build }}
          path: export/${{ matrix.build }}/windows/bin
